version: "3"
services:
    openvpn:
        container_name: openvpn
        image: kylemanna/openvpn
        ports:
            - "1194:1194/udp"
        networks:
            - dvp
        volumes:
            - /etc/openvpn:/etc/openvpn
        cap_add:
            - NET_ADMIN
        restart: always

    pihole:
        container_name: pihole
        image: pihole/pihole:latest
        ports:
        #   - "53:53/tcp"
        #   - "53:53/udp"
        #   - "67:67/udp"
        #   - "80:80/tcp"
        #   - "443:443/tcp"
        networks:
            dvp:
                ipv4_address: 172.28.28.28
        environment:
            TZ: 'UTC'
        volumes:
            - './etc-pihole/:/etc/pihole/'
            - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
        dns:
            - 127.0.0.1
            - 1.1.1.1
        cap_add:
            - NET_ADMIN
        restart: always

networks:
    dvp:
        ipam:
            driver: default
            config:
                - subnet: 172.28.28.0/24
